<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EN911042" failures="1" tests="4" name="uiTests.HomePageTests" time="151.214" errors="0" timestamp="2020-10-08T19:19:59 COT" skipped="0">
  <testcase classname="uiTests.HomePageTests" name="validateLogin" time="38.015"/>
  <system-out/>
  <testcase classname="uiTests.HomePageTests" name="validateHomePage" time="47.608"/>
  <system-out/>
  <testcase classname="uiTests.HomePageTests" name="validatePersonalProject" time="49.044"/>
  <system-out/>
  <testcase classname="uiTests.HomePageTests" name="validateScreenShotError" time="16.547">
    <failure message="expected [Log Out] but found [Log In]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Log Out] but found [Log In]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at uiTests.HomePageTests.validateScreenShotError(HomePageTests.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- validateScreenShotError -->
  <system-out/>
</testsuite> <!-- uiTests.HomePageTests -->
