<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EN911042" failures="1" tests="4" name="HomePageTest" time="151.304" errors="0" timestamp="2020-10-08T19:15:54 COT">
  <testcase classname="uiTests.HomePageTests" name="validateLogin" time="20.016"/>
  <testcase classname="uiTests.HomePageTests" name="validateHomePage" time="26.64"/>
  <testcase classname="uiTests.HomePageTests" name="validatePersonalProject" time="27.054"/>
  <testcase classname="uiTests.HomePageTests" name="validateScreenShotError" time="0.204">
    <failure type="java.lang.AssertionError" message="expected [Log Out] but found [Log In]">
      <![CDATA[java.lang.AssertionError: expected [Log Out] but found [Log In]
at uiTests.HomePageTests.validateScreenShotError(HomePageTests.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- validateScreenShotError -->
</testsuite> <!-- HomePageTest -->
